version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.1
  - dependency-name: ember-cli-htmlbars-inline-precompile
    versions:
    - 3.0.1
  - dependency-name: ember-cli
    versions:
    - 3.24.0
